# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jb6opKP0-ABPYCtoSvUr-rvMUOQbOiaf
"""

# ==============================
# QUESTION 1
# ==============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# ------------------------------
# Given Data
# ------------------------------
mu = np.array([0.10, 0.25, 0.15])

C = np.array([
    [0.005, -0.010, 0.004],
    [-0.010, 0.040, -0.002],
    [0.004, -0.002, 0.023]
])

n = len(mu)

# ------------------------------
# Helper Functions
# ------------------------------
def port_return(w):
    return np.dot(w, mu)

def port_risk(w):
    return np.sqrt(w.T @ C @ w)

# ------------------------------
# Constraints
# ------------------------------
bounds = [(0, 1)] * n
sum_constraint = {'type': 'eq', 'fun': lambda w: np.sum(w) - 1}

# =========================================================
# (A) Efficient Frontier
# =========================================================
target_returns = np.linspace(min(mu), max(mu), 100)
risks = []
weights = []

for R in target_returns:
    constraints = [
        sum_constraint,
        {'type': 'eq', 'fun': lambda w, R=R: port_return(w) - R}
    ]

    res = minimize(
        lambda w: w.T @ C @ w,
        x0=np.ones(n)/n,
        bounds=bounds,
        constraints=constraints
    )

    risks.append(np.sqrt(res.fun))
    weights.append(res.x)

plt.figure(figsize=(8,6))
plt.plot(risks, target_returns)
plt.xlabel("Risk (Std Dev)")
plt.ylabel("Return")
plt.title("Efficient Frontier")
plt.grid()
plt.show()

# =========================================================
# (B) Table for 10 Portfolios
# =========================================================
idx = np.linspace(0, 99, 10, dtype=int)
data = []

for i in idx:
    data.append([*weights[i], target_returns[i], risks[i]])

df = pd.DataFrame(
    data,
    columns=["w1", "w2", "w3", "Return", "Risk"]
)

print("\nTable of 10 Efficient Portfolios:\n")
print(df)

# =========================================================
# (C) Max & Min Return for 15% Risk
# =========================================================
target_risk = 0.15

risk_constraint = {'type': 'eq', 'fun': lambda w: port_risk(w) - target_risk}

res_max = minimize(
    lambda w: -port_return(w),
    np.ones(n)/n,
    bounds=bounds,
    constraints=[sum_constraint, risk_constraint]
)

res_min = minimize(
    lambda w: port_return(w),
    np.ones(n)/n,
    bounds=bounds,
    constraints=[sum_constraint, risk_constraint]
)

print("\n15% Risk Portfolios:")
print("Max Return:", port_return(res_max.x), "Weights:", res_max.x)
print("Min Return:", port_return(res_min.x), "Weights:", res_min.x)

# =========================================================
# (D) Minimum Risk for 18% Return
# =========================================================
target_R = 0.18

constraints = [
    sum_constraint,
    {'type': 'eq', 'fun': lambda w: port_return(w) - target_R}
]

res = minimize(
    lambda w: w.T @ C @ w,
    np.ones(n)/n,
    bounds=bounds,
    constraints=constraints
)

print("\n18% Return Portfolio:")
print("Weights:", res.x)
print("Risk:", np.sqrt(res.fun))

# =========================================================
# (E) Market Portfolio & CML (rf = 8%)
# =========================================================
rf = 0.08

def neg_sharpe(w):
    return -(port_return(w) - rf) / port_risk(w)

res = minimize(
    neg_sharpe,
    np.ones(n)/n,
    bounds=bounds,
    constraints=[sum_constraint]
)

w_m = res.x
ret_m = port_return(w_m)
risk_m = port_risk(w_m)

print("\nMarket Portfolio:")
print("Weights:", w_m)
print("Return:", ret_m)
print("Risk:", risk_m)

# Plot CML
x = np.linspace(0, max(risks), 100)
y = rf + (ret_m - rf)/risk_m * x

plt.figure(figsize=(8,6))
plt.plot(risks, target_returns, label="Efficient Frontier")
plt.plot(x, y, 'r--', label="CML")
plt.scatter(risk_m, ret_m, c='black', label="Market Portfolio")
plt.legend()
plt.grid()
plt.show()

# =========================================================
# (F) Portfolios with 10% and 25% Risk
# =========================================================
alpha_10 = 0.10 / risk_m
alpha_25 = 0.25 / risk_m

print("\nPortfolios with Risk-Free Asset:")
print("10% Risk Portfolio (risky weights):", alpha_10 * w_m)
print("25% Risk Portfolio (risky weights):", alpha_25 * w_m)

# ==============================
# GENERATING CSV FILE
# ==============================

import numpy as np
import pandas as pd

np.random.seed(42)

# Parameters
n_assets = 10
n_days = 100

# Generate synthetic daily returns
daily_returns = np.random.normal(
    loc=0.0005,
    scale=0.02,
    size=(n_days, n_assets)
)

# Convert to prices
prices = 100 * np.exp(np.cumsum(daily_returns, axis=0))

# Create DataFrame
dates = pd.date_range("2025-01-01", periods=n_days)
stocks = [f"Stock_{i+1}" for i in range(n_assets)]

price_df = pd.DataFrame(prices, index=dates, columns=stocks)

# Save to CSV
price_df.to_csv("stocks.csv")

print("stocks.csv file created successfully!")

# ==============================
# QUESTION 2 : USING CSV FILE
# ==============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Load CSV
data = pd.read_csv("stocks.csv", index_col=0)

# Compute returns
returns = data.pct_change().dropna()

# Annualized mean & covariance
mu = returns.mean() * 252
C = returns.cov() * 252
n = len(mu)

# Helper functions
def port_return(w):
    return np.dot(w, mu)

def port_risk(w):
    return np.sqrt(w.T @ C @ w)

bounds = [(0,1)] * n
sum_constraint = {'type': 'eq', 'fun': lambda w: np.sum(w) - 1}

# -------------------------------------------------
# (A) Efficient Frontier
# -------------------------------------------------
target_returns = np.linspace(mu.min(), mu.max(), 100)
risks = []

for R in target_returns:
    constraints = [
        sum_constraint,
        {'type': 'eq', 'fun': lambda w, R=R: port_return(w) - R}
    ]

    res = minimize(
        lambda w: w.T @ C @ w,
        np.ones(n)/n,
        bounds=bounds,
        constraints=constraints
    )

    risks.append(np.sqrt(res.fun))

plt.plot(risks, target_returns)
plt.xlabel("Risk")
plt.ylabel("Return")
plt.title("Efficient Frontier")
plt.grid()
plt.show()

# -------------------------------------------------
# (B) Market Portfolio (rf = 5%)
# -------------------------------------------------
rf = 0.05

def neg_sharpe(w):
    return -(port_return(w) - rf) / port_risk(w)

res = minimize(
    neg_sharpe,
    np.ones(n)/n,
    bounds=bounds,
    constraints=[sum_constraint]
)

w_m = res.x
ret_m = port_return(w_m)
risk_m = port_risk(w_m)

print("\nMarket Portfolio Weights:")
print(pd.Series(w_m, index=mu.index))

# -------------------------------------------------
# (C) Capital Market Line
# -------------------------------------------------
x = np.linspace(0, risk_m * 1.5, 100)
y = rf + (ret_m - rf)/risk_m * x

plt.plot(x, y)
plt.xlabel("Risk")
plt.ylabel("Return")
plt.title("Capital Market Line")
plt.grid()
plt.show()

# -------------------------------------------------
# (D) Security Market Line
# -------------------------------------------------
beta = (C @ w_m) / (w_m.T @ C @ w_m)
capm_returns = rf + beta * (ret_m - rf)

plt.scatter(beta, mu)
plt.plot(beta, capm_returns)
plt.xlabel("Beta")
plt.ylabel("Expected Return")
plt.title("Security Market Line")
plt.grid()
plt.show()

