# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t09P5vP1t5QCD_G2gRENCqQor3o5FQ1
"""

import numpy as np
import matplotlib.pyplot as plt
def binomial_option_price(S0, K, T, r, sigma, M):

    dt = T / M

    # Up and Down factors
    u = np.exp(sigma * np.sqrt(dt) + (r - 0.5 * sigma**2) * dt)
    d = np.exp(-sigma * np.sqrt(dt) + (r - 0.5 * sigma**2) * dt)

    # Risk-neutral probability
    p = (np.exp(r * dt) - d) / (u - d)

    # No-arbitrage condition
    if not (0 < p < 1):
        raise ValueError("No-arbitrage condition violated")

    # Stock prices at maturity
    ST = np.array([S0 * (u**j) * (d**(M - j)) for j in range(M + 1)])

    # Payoffs
    call_payoff = np.maximum(ST - K, 0)
    put_payoff  = np.maximum(K - ST, 0)

    # Backward induction
    discount = np.exp(-r * dt)

    for _ in range(M):
        call_payoff = discount * (p * call_payoff[1:] + (1 - p) * call_payoff[:-1])
        put_payoff  = discount * (p * put_payoff[1:]  + (1 - p) * put_payoff[:-1])

    return call_payoff[0], put_payoff[0]

S0 = 9
K = 10
T = 3
r = 0.06
sigma = 0.3

M_values = [1, 5, 10, 20, 50, 100, 200]

print("M\tCall Price\tPut Price")
print("-" * 35)

for M in M_values:
    call, put = binomial_option_price(S0, K, T, r, sigma, M)
    print(f"{M}\t{call:.6f}\t{put:.6f}")

M_range_1 = range(1, 201)

call_prices_1 = []
put_prices_1 = []

for M in M_range_1:
    call, put = binomial_option_price(S0, K, T, r, sigma, M)
    call_prices_1.append(call)
    put_prices_1.append(put)

plt.figure()
plt.plot(M_range_1, call_prices_1, label="Call Option")
plt.plot(M_range_1, put_prices_1, label="Put Option")
plt.xlabel("Number of Steps (M)")
plt.ylabel("Option Price")
plt.title("Option Price vs M (Step = 1)")
plt.legend()
plt.grid()
plt.show()

def option_price_at_time(S_t, K, T_remaining, r, sigma, M_remaining):
    return binomial_option_price(S_t, K, T_remaining, r, sigma, M_remaining)
M = 20
dt = T / M

times = [0, 0.30, 0.75, 1.50, 2.70]

print("Time\tCall Price\tPut Price")
print("-" * 35)

for t in times:
    step = int(t / dt)
    T_remain = T - t
    M_remain = M - step

    # Expected stock price under risk-neutral measure
    S_t = S0 * np.exp(r * t)

    call, put = option_price_at_time(S_t, K, T_remain, r, sigma, M_remain)
    print(f"{t:.2f}\t{call:.6f}\t{put:.6f}")

