# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrUyqWN8r2O6ecZzIQzsKSEad1HrjGY5
"""

import numpy as np
import matplotlib.pyplot as plt
import time

# ============================================================
# COMMON FUNCTIONS
# ============================================================

def ud_set1(sigma, dt):
    u = np.exp(sigma * np.sqrt(dt))
    d = np.exp(-sigma * np.sqrt(dt))
    return u, d

def ud_set2(sigma, r, dt):
    u = np.exp(sigma * np.sqrt(dt) + (r - 0.5 * sigma**2) * dt)
    d = np.exp(-sigma * np.sqrt(dt) + (r - 0.5 * sigma**2) * dt)
    return u, d

def european_binomial_price(S0, K, T, r, sigma, M, u, d):
    dt = T / M
    p = (np.exp(r * dt) - d) / (u - d)

    ST = np.array([S0 * (u**j) * (d**(M - j)) for j in range(M + 1)])
    call = np.maximum(ST - K, 0)
    put  = np.maximum(K - ST, 0)

    for _ in range(M):
        call = np.exp(-r * dt) * (p * call[1:] + (1 - p) * call[:-1])
        put  = np.exp(-r * dt) * (p * put[1:]  + (1 - p) * put[:-1])

    return call[0], put[0]

# ============================================================
# QUESTION 1: EUROPEAN CALL & PUT + GRAPHS
# ============================================================

print("\n================ QUESTION 1 =================\n")

S0, K, T, r, sigma, M = 100, 100, 1, 0.08, 0.2, 100
dt = T / M

u1, d1 = ud_set1(sigma, dt)
u2, d2 = ud_set2(sigma, r, dt)

call1, put1 = european_binomial_price(S0, K, T, r, sigma, M, u1, d1)
call2, put2 = european_binomial_price(S0, K, T, r, sigma, M, u2, d2)

print("Set 1 -> Call:", call1, " Put:", put1)
print("Set 2 -> Call:", call2, " Put:", put2)

# ---------- Sensitivity Plots ----------

# (A) S0
S_vals = np.linspace(60, 140, 30)
prices = [european_binomial_price(S, K, T, r, sigma, M, u2, d2)[0] for S in S_vals]
plt.plot(S_vals, prices)
plt.xlabel("S(0)")
plt.ylabel("Call Price")
plt.title("Call Price vs S(0)")
plt.show()

# (B) K
K_vals = np.linspace(60, 140, 30)
prices = [european_binomial_price(S0, k, T, r, sigma, M, u2, d2)[0] for k in K_vals]
plt.plot(K_vals, prices)
plt.xlabel("K")
plt.ylabel("Call Price")
plt.title("Call Price vs Strike")
plt.show()

# (C) r
r_vals = np.linspace(0.01, 0.15, 30)
prices = []
for r_ in r_vals:
    u, d = ud_set2(sigma, r_, dt)
    prices.append(european_binomial_price(S0, K, T, r_, sigma, M, u, d)[0])
plt.plot(r_vals, prices)
plt.xlabel("r")
plt.ylabel("Call Price")
plt.title("Call Price vs Interest Rate")
plt.show()

# (D) sigma
sig_vals = np.linspace(0.05, 0.5, 30)
prices = []
for s in sig_vals:
    u, d = ud_set2(s, r, dt)
    prices.append(european_binomial_price(S0, K, T, r, s, M, u, d)[0])
plt.plot(sig_vals, prices)
plt.xlabel("sigma")
plt.ylabel("Call Price")
plt.title("Call Price vs Volatility")
plt.show()

# (E) M for different K
M_vals = [10, 25, 50, 100, 200]
Ks = [95, 100, 105]

for k in Ks:
    prices = []
    for m in M_vals:
        dt = T / m
        u, d = ud_set2(sigma, r, dt)
        prices.append(european_binomial_price(S0, k, T, r, sigma, m, u, d)[0])
    plt.plot(M_vals, prices, label=f"K={k}")

plt.xlabel("M")
plt.ylabel("Call Price")
plt.legend()
plt.title("Convergence with M")
plt.show()

# ============================================================
# QUESTION 2: LOOKBACK OPTION – BASIC BINOMIAL
# ============================================================

print("\n================ QUESTION 2 =================\n")
print("NOTE: Basic binomial is exponential. Using small M only.\n")

def lookback_basic(S0, T, r, sigma, M):
    dt = T / M
    u = np.exp(sigma*np.sqrt(dt) + (r - 0.5*sigma**2)*dt)
    d = np.exp(-sigma*np.sqrt(dt) + (r - 0.5*sigma**2)*dt)
    p = (np.exp(r*dt) - d) / (u - d)

    paths = [(S0, S0)]
    for _ in range(M):
        new_paths = []
        for price, mx in paths:
            new_paths.append((price*u, max(mx, price*u)))
            new_paths.append((price*d, max(mx, price*d)))
        paths = new_paths

    payoff = np.array([mx - price for price, mx in paths])
    probs = np.array([
        p**bin(i).count("1") * (1-p)**(M - bin(i).count("1"))
        for i in range(len(payoff))
    ])

    return np.exp(-r*T) * np.sum(payoff * probs)

# (A) Prices
for M in [5, 10]:
    print(f"M = {M}, Lookback Price = {lookback_basic(100,1,0.08,0.2,M)}")

# (C) Intermediate values for M = 5
print("\nIntermediate states for M = 5:\n")
def intermediate_states_M5():
    S0, T, r, sigma, M = 100, 1, 0.08, 0.2, 5
    dt = T / M
    u, d = ud_set2(sigma, r, dt)

    states = [(S0, S0)]
    for t in range(1, M+1):
        new_states = []
        for price, mx in states:
            new_states.append((price*u, max(mx, price*u)))
            new_states.append((price*d, max(mx, price*d)))
        states = new_states
        print(f"Time {t}: {states}")

intermediate_states_M5()

# ============================================================
# QUESTION 3: LOOKBACK OPTION – MARKOV METHOD
# ============================================================

print("\n================ QUESTION 3 =================\n")

def lookback_markov(S0, T, r, sigma, M):
    dt = T / M
    u, d = ud_set2(sigma, r, dt)

    states = {(0, S0): 1.0}
    for t in range(1, M+1):
        new_states = {}
        for (k, mx), prob in states.items():
            Su = S0 * (u**(k+1)) * (d**(t-k-1))
            Sd = S0 * (u**k) * (d**(t-k))

            mu, md = max(mx, Su), max(mx, Sd)
            new_states[(k+1, mu)] = new_states.get((k+1, mu), 0) + prob
            new_states[(k, md)]   = new_states.get((k, md), 0) + prob

        states = new_states

    payoff = 0
    for (k, mx), prob in states.items():
        ST = S0 * (u**k) * (d**(M-k))
        payoff += prob * (mx - ST)

    return np.exp(-r*T) * payoff

# Prices & timing
for M in [25, 50, 100]:
    start = time.time()
    price = lookback_markov(100,1,0.08,0.2,M)
    print(f"M = {M}, Markov Price = {price}, Time = {time.time()-start}")

